### ISSUE TITLE
win版0.1.1进度卡住

### ISSUE THREAD

**Issue by dandannnn** [qicfan/q115-strm#2]
按照作者的配置第一次运行main.exe -e=Media -c=0 运行到后面会卡住post，strm生成应该是完成了。
第二次运行main.exe -e=Media -c=1  想复制元数据，但是还是卡住post，文件夹下面并没有jpg或者字幕文件，是命令不对吗？
![b883750f8a9de610f14948f86caf715](https://github.com/user-attachments/assets/fa55e881-e265-4c02-b416-5ad6dc72413c)

**Comment by qicfan** [comment]
1. 最后一个POST是在删除临时生成的目录树文件
2. 最后卡住没有输出可能的原因：
>   - 网盘挂载文件夹设置错误，导致元数据的源文件不存在
>   - 元数据文件过大，如果复制缓慢会很长一段时间没有输出

针对这两个问题，我增加了对应的日志，可以下载0.1.2版本试一下。

**Comment by dandannnn** [comment]
win版cloud_mount_root_dir: 115网盘的挂在路径根目录， 例如：/CloudNAS/115
请问作者这里一定要本地挂载用CD2或者alist挂载到真实路径，才可以复制元数据，还是说不需要借助CD2挂载就可以在线获取

**Comment by qicfan** [comment]
需要CD2或者ALIST挂载到真实路径才能复制，否则不仅复制失败生成的STRM也没办法播放。

**Comment by qicfan** [comment]
提示不存在就是路径不对，需要核对路径
