### ISSUE TITLE
本地残留strm

### ISSUE THREAD

**Issue by palonnn** [qicfan/q115-strm#3]
网盘删除文件，更改名称，执行脚本后是重新生成文件，而旧的文件没有清除，只能手动删除。比如网盘目录下的影视名 唐人街探案，本地strm文件名唐人街探案.strm，我删除这个影视后执行脚本，本地依然残留strm文件，或者我更改名称，改为唐人街探案 (2015)再次执行脚本后，本地生成了唐人街探案 (2015).strm，未更改名称前的strm也存在，唐人街探案.strm。

**Comment by qicfan** [comment]
感谢反馈，这是个已知问题，我现在是手动删除对应的子目录然后重建的。预计0.1.3版本解决

**Comment by qicfan** [comment]
0.1.3已发布，可以试一下。
